import { StyleSheet } from 'react-native';
import { theme } from '../../../../config/theme';

export const styles = StyleSheet.create({
  scrollContent: {
    padding: 16,
    paddingBottom: 24,
    gap: 14,
  },
  card: {
    backgroundColor: theme.colors.white,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1.5,
    borderColor: theme.colors.borderGray,
  },
  cardSelected: {
    borderColor: theme.colors.purple,
    backgroundColor: '#FAF5FF',
  },
  cardHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  iconSquareLightning: {
    width: 48,
    height: 48,
    borderRadius: 14,
    backgroundColor: '#FFFBEB',
    borderWidth: 1,
    borderColor: '#FDE68A',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  iconSquareCalendar: {
    width: 48,
    height: 48,
    borderRadius: 14,
    backgroundColor: '#F3E8FF',
    borderWidth: 1,
    borderColor: '#E9D5FF',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  cardInfo: {
    flex: 1,
    paddingRight: 8,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 2,
  },
  cardTitle: {
    fontFamily: theme.fonts.bold,
    fontSize: 15,
    color: theme.colors.navy,
  },
  fastestBadgePill: {
    backgroundColor: '#FEF3C7',
    paddingVertical: 2,
    paddingHorizontal: 8,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  fastestBadgePillText: {
    fontFamily: theme.fonts.bold,
    fontSize: 11,
    color: '#92400E',
  },
  cardSubtitle: {
    fontFamily: theme.fonts.medium,
    fontSize: 12,
    color: theme.colors.gray,
    lineHeight: 16,
  },
  readyStatusPill: {
    backgroundColor: '#E6F4EA',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    alignSelf: 'flex-start',
    marginTop: 6,
  },
  readyStatusPillText: {
    fontFamily: theme.fonts.medium,
    fontSize: 11,
    color: '#15803D',
  },
  radioCircle: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: theme.colors.purple,
    justifyContent: 'center',
    alignItems: 'center',
  },
  radioInner: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: theme.colors.purple,
  },
  cardSection: {
    backgroundColor: theme.colors.white,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: theme.colors.borderGray,
  },
  sectionTitle: {
    fontFamily: theme.fonts.bold,
    fontSize: 14,
    color: theme.colors.navy,
    marginBottom: 10,
  },
  radioOptionRow: {
    flexDirection: 'row',
    gap: 24,
    marginTop: 6,
  },
  radioOption: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  radioText: {
    fontFamily: theme.fonts.semibold,
    fontSize: 14,
    color: theme.colors.darkText,
  },
  timeOptionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    gap: 12,
  },
  timeOptionLabel: {
    fontFamily: theme.fonts.bold,
    fontSize: 14,
    color: theme.colors.navy,
  },
  accordionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  accordionHeaderTitle: {
    fontFamily: theme.fonts.bold,
    fontSize: 14,
    color: theme.colors.navy,
  },
  accordionBody: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
  },
  policySubTitle: {
    fontFamily: theme.fonts.semibold,
    fontSize: 12,
    color: theme.colors.darkText,
    marginBottom: 4,
  },
  policyBulletRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 6,
    marginBottom: 14,
  },
  bulletDot: {
    fontFamily: theme.fonts.bold,
    fontSize: 12,
    color: theme.colors.gray,
  },
  policyBulletText: {
    flex: 1,
    fontFamily: theme.fonts.medium,
    fontSize: 11.5,
    color: theme.colors.gray,
    lineHeight: 16,
  },
  policyBadgesRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    flexWrap: 'wrap',
  },
  policyBadgeItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  policyBadgeText: {
    fontFamily: theme.fonts.semibold,
    fontSize: 10.5,
    color: '#7C3AED',
  },
  bottomStickyBar: {
    backgroundColor: theme.colors.white,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
    shadowColor: theme.colors.pureBlack,
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 8,
  },
  priceCol: {},
  priceValue: {
    fontFamily: theme.fonts.bold,
    fontSize: 18,
    color: theme.colors.navy,
  },
  perSessionText: {
    fontFamily: theme.fonts.medium,
    fontSize: 12,
    color: theme.colors.gray,
  },
  consultationLabel: {
    fontFamily: theme.fonts.medium,
    fontSize: 11,
    color: theme.colors.gray,
  },
  bookSessionBtn: {
    backgroundColor: '#7C3AED',
    paddingVertical: 12,
    paddingHorizontal: 32,
    borderRadius: 30,
    shadowColor: '#7C3AED',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
  },
  bookSessionBtnText: {
    fontFamily: theme.fonts.bold,
    fontSize: 14,
    color: theme.colors.white,
  },
  fullWidthContinueBtn: {
    flex: 1,
    backgroundColor: '#7C3AED',
    paddingVertical: 14,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#7C3AED',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
  },
});
