import { StyleSheet } from 'react-native';
import { theme } from '../../../../config/theme';

export const styles = StyleSheet.create({
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 24,
    justifyContent: 'space-between',
  },
  topSection: {
    width: '100%',
  },
  bottomSection: {
    width: '100%',
    paddingBottom: 12,
  },
  inputSectionLabel: {
    fontFamily: theme.fonts.bold,
    fontSize: 14,
    color: theme.colors.dark,
    marginBottom: 10,
    marginTop: 8,
  },
  amountInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.colors.borderLight,
    borderRadius: 14,
    paddingHorizontal: 16,
    height: 46,
    backgroundColor: theme.colors.white,
    marginBottom: 20,
  },
  rupeeSymbol: {
    fontFamily: theme.fonts.bold,
    fontSize: 18,
    color: theme.colors.greenIcon,
    marginRight: 10,
  },
  amountInput: {
    flex: 1,
    fontFamily: theme.fonts.semibold,
    fontSize: 15,
    color: theme.colors.dark,
  },
  quickAmountRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 24,
  },
  quickPill: {
    flex: 1,
    height: 42,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.colors.borderLight,
    backgroundColor: theme.colors.white,
    justifyContent: 'center',
    alignItems: 'center',
  },
  quickPillActive: {
    backgroundColor: theme.colors.purple,
    borderColor: theme.colors.purple,
  },
  quickPillText: {
    fontFamily: theme.fonts.medium,
    fontSize: 13,
    color: theme.colors.dark,
  },
  quickPillTextActive: {
    fontFamily: theme.fonts.bold,
    color: theme.colors.white,
  },
  infoCalloutBoxAmber: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.cardCream,
    borderRadius: 12,
    padding: 12,
    marginBottom: 20,
    gap: 10,
    borderWidth: 1,
    borderColor: theme.colors.softAmber,
  },
  infoCalloutText: {
    flex: 1,
    fontFamily: theme.fonts.medium,
    fontSize: 12,
    color: theme.colors.darkText,
    lineHeight: 16,
  },
  payButton: {
    backgroundColor: theme.colors.purple,
    borderRadius: 14,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 14,
  },
  payButtonText: {
    fontFamily: theme.fonts.bold,
    fontSize: 15,
    color: theme.colors.white,
  },
  securedRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
  },
  securedText: {
    fontFamily: theme.fonts.medium,
    fontSize: 12,
    color: theme.colors.gray,
  },
  successModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  successModalCard: {
    width: '100%',
    backgroundColor: theme.colors.white,
    borderRadius: 24,
    padding: 24,
    alignItems: 'center',
    shadowColor: theme.colors.pureBlack,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 5,
  },
  successIconCircle: {
    width: 68,
    height: 68,
    borderRadius: 34,
    backgroundColor: theme.colors.lightGreenBg,
    borderWidth: 1.5,
    borderColor: '#A7F3D0',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  successTitle: {
    fontFamily: theme.fonts.bold,
    fontSize: 18,
    color: theme.colors.navy,
    marginBottom: 8,
    textAlign: 'center',
  },
  successSubtitle: {
    fontFamily: theme.fonts.regular,
    fontSize: 13.5,
    color: theme.colors.gray,
    textAlign: 'center',
    marginBottom: 20,
    lineHeight: 19,
  },
  successDoneButton: {
    backgroundColor: theme.colors.purple,
    borderRadius: 14,
    height: 46,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  successDoneButtonText: {
    fontFamily: theme.fonts.bold,
    fontSize: 14,
    color: theme.colors.white,
  },
});
