import { StyleSheet } from 'react-native';
import { theme } from '../../../../config/theme';

export const styles = StyleSheet.create({
  scrollContent: {
    padding: 20,
    paddingBottom: 32,
  },
  progressCard: {
    backgroundColor: theme.colors.white,
    borderRadius: 40,
    paddingVertical: 12,
    paddingHorizontal: 18,
    marginBottom: 24,
    borderWidth: 1.5,
    borderColor: theme.colors.borderGray,
    shadowColor: theme.colors.pureBlack,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 2,
  },
  progressHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  progressLabel: {
    fontFamily: theme.fonts.bold,
    fontSize: 12,
    color: theme.colors.purple,
  },
  progressStepText: {
    fontFamily: theme.fonts.bold,
    fontSize: 12,
    color: theme.colors.darkText,
  },
  progressBarTrack: {
    height: 10,
    backgroundColor: theme.colors.borderGray,
    borderRadius: 5,
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: theme.colors.accentLime,
    borderRadius: 5,
  },
  questionHeader: {
    marginBottom: 24,
  },
  questionTitle: {
    fontFamily: theme.fonts.bold,
    fontSize: 22,
    color: theme.colors.navy,
    lineHeight: 30,
    marginBottom: 6,
  },
  questionSubtitle: {
    fontFamily: theme.fonts.medium,
    fontSize: 13,
    color: theme.colors.gray,
  },
  optionsList: {
    gap: 14,
  },
  optionCard: {
    backgroundColor: theme.colors.white,
    borderRadius: 50,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderWidth: 1.5,
    borderColor: theme.colors.borderGray,
    shadowColor: theme.colors.pureBlack,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 4,
    elevation: 2,
  },
  optionCardSelected: {
    backgroundColor: theme.colors.softYellowBg,
    borderColor: theme.colors.softYellowBorder,
  },
  optionCardSelectedViewMode: {
    backgroundColor: theme.colors.borderGray,
    borderColor: theme.colors.lightGray,
  },
  optionContentRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  iconWrapper: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: theme.colors.white,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
    shadowColor: theme.colors.pureBlack,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
    borderWidth: 1,
    borderColor: theme.colors.borderLight,
  },
  optionTextCol: {
    flex: 1,
  },
  optionTitle: {
    fontFamily: theme.fonts.bold,
    fontSize: 13.5,
    color: theme.colors.navy,
    lineHeight: 18,
  },
  optionTitleSelected: {
    color: theme.colors.navy,
  },
  optionSubtitle: {
    fontFamily: theme.fonts.medium,
    fontSize: 11.5,
    color: theme.colors.gray,
    marginTop: 3,
    lineHeight: 15,
  },
  bottomBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 16,
    backgroundColor: 'transparent',
  },
  previousBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 8,
    paddingHorizontal: 4,
  },
  previousBtnText: {
    fontFamily: theme.fonts.bold,
    fontSize: 13,
    color: theme.colors.navy,
    letterSpacing: 0.5,
  },
  submitBtn: {
    backgroundColor: theme.colors.purple,
    paddingVertical: 12,
    paddingHorizontal: 36,
    borderRadius: 30,
    shadowColor: theme.colors.purple,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
  },
  submitBtnText: {
    fontFamily: theme.fonts.bold,
    fontSize: 14,
    color: theme.colors.white,
  },
  nextTextBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 8,
    paddingHorizontal: 4,
  },
  nextTextBtnText: {
    fontFamily: theme.fonts.bold,
    fontSize: 13,
    color: theme.colors.navy,
    letterSpacing: 0.5,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: theme.colors.overlayModal,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  confirmationCard: {
    width: '100%',
    backgroundColor: theme.colors.white,
    borderRadius: 24,
    padding: 24,
    alignItems: 'center',
    shadowColor: theme.colors.pureBlack,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
    position: 'relative',
  },
  closeBtn: {
    position: 'absolute',
    top: 16,
    right: 16,
    padding: 6,
    zIndex: 10,
  },
  closeBtnText: {
    fontSize: 16,
    color: theme.colors.gray,
    fontFamily: theme.fonts.bold,
  },
  greenStarBadge: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: theme.colors.indicatorGreen,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 8,
    marginBottom: 16,
  },
  confirmationTitle: {
    fontFamily: theme.fonts.bold,
    fontSize: 18,
    color: theme.colors.darkEmerald,
    letterSpacing: 0.5,
    marginBottom: 6,
  },
  confirmationSubtitle: {
    fontFamily: theme.fonts.medium,
    fontSize: 13,
    color: theme.colors.gray,
    textAlign: 'center',
    marginBottom: 20,
  },
  modalDivider: {
    width: '100%',
    height: 1,
    backgroundColor: theme.colors.borderGray,
    marginBottom: 16,
  },
  modalDoctorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    gap: 12,
  },
  modalAvatarWrapper: {
    position: 'relative',
  },
  verifiedDot: {
    position: 'absolute',
    bottom: -2,
    right: -2,
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: theme.colors.indicatorGreen,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: theme.colors.white,
  },
  modalDoctorMeta: {
    flex: 1,
  },
  modalDoctorHeader: {
    fontFamily: theme.fonts.bold,
    fontSize: 15,
    color: theme.colors.navy,
  },
  modalDoctorName: {
    fontFamily: theme.fonts.medium,
    fontSize: 12,
    color: theme.colors.gray,
  },
  modalDoctorSub: {
    fontFamily: theme.fonts.medium,
    fontSize: 12,
    color: theme.colors.gray,
  },
});
