import { StyleSheet } from 'react-native';
import { theme } from '../../../../config/theme';

export const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 110,
  },
  headingTitle: {
    fontFamily: theme.fonts.bold,
    fontSize: 15,
    color: theme.colors.dark,
    marginBottom: 12,
  },
  noticeBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: theme.colors.softCream,
    borderRadius: 14,
    padding: 12,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: theme.colors.amberStar,
    gap: 8,
  },
  noticeIcon: {
    marginTop: 2,
  },
  noticeText: {
    flex: 1,
    fontFamily: theme.fonts.regular,
    fontSize: 12,
    color: theme.colors.darkText,
    lineHeight: 17,
  },
  expertCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.white,
    borderRadius: 16,
    padding: 14,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: theme.colors.borderLight,
  },
  avatarWrapper: {
    position: 'relative',
    marginRight: 12,
  },
  avatarBox: {
    width: 50,
    height: 50,
    borderRadius: 25,
    overflow: 'hidden',
    backgroundColor: theme.colors.softPurpleBg,
  },
  badgeOverlay: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    backgroundColor: theme.colors.white,
    borderRadius: 7,
  },
  expertTextCol: {
    flex: 1,
  },
  expertTitle: {
    fontFamily: theme.fonts.bold,
    fontSize: 14.5,
    color: theme.colors.dark,
    marginBottom: 1,
  },
  doctorName: {
    fontFamily: theme.fonts.medium,
    fontSize: 12,
    color: theme.colors.gray,
    marginBottom: 1,
  },
  specialty: {
    fontFamily: theme.fonts.regular,
    fontSize: 11.5,
    color: theme.colors.gray,
  },
  accordionCard: {
    backgroundColor: theme.colors.softWarmYellow,
    borderRadius: 16,
    padding: 14,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: theme.colors.amberStar,
  },
  accordionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  accordionTitle: {
    fontFamily: theme.fonts.bold,
    fontSize: 13.5,
    color: theme.colors.dark,
  },
  accordionContent: {
    marginTop: 10,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: 'rgba(245, 158, 11, 0.2)',
  },
  policySubtitle: {
    fontFamily: theme.fonts.bold,
    fontSize: 12,
    color: theme.colors.darkText,
    marginBottom: 4,
  },
  policyBody: {
    fontFamily: theme.fonts.regular,
    fontSize: 11.5,
    color: theme.colors.gray,
    lineHeight: 16,
    marginBottom: 10,
  },
  policyBadgesRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  policyPill: {
    backgroundColor: theme.colors.softLavender,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  policyPillText: {
    fontFamily: theme.fonts.bold,
    fontSize: 10.5,
    color: theme.colors.purple,
  },
  securePill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  securePillText: {
    fontFamily: theme.fonts.medium,
    fontSize: 10.5,
    color: theme.colors.purple,
  },
  durationCard: {
    backgroundColor: theme.colors.white,
    borderRadius: 16,
    padding: 16,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: theme.colors.borderLight,
  },
  cardLabel: {
    fontFamily: theme.fonts.bold,
    fontSize: 13.5,
    color: theme.colors.dark,
    marginBottom: 10,
  },
  radioRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  radioOuter: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: theme.colors.purple,
    justifyContent: 'center',
    alignItems: 'center',
  },
  radioInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: theme.colors.purple,
  },
  radioText: {
    fontFamily: theme.fonts.bold,
    fontSize: 14,
    color: theme.colors.dark,
  },
  dateCard: {
    backgroundColor: theme.colors.white,
    borderRadius: 16,
    padding: 16,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: theme.colors.borderLight,
  },
  dateHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  monthTitle: {
    fontFamily: theme.fonts.bold,
    fontSize: 13.5,
    color: theme.colors.dark,
  },
  calendarIconBtn: {
    padding: 4,
    backgroundColor: theme.colors.softLavender,
    borderRadius: 8,
  },
  datePillsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 8,
  },
  datePill: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 6,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.bgLight,
    borderWidth: 1,
    borderColor: theme.colors.borderGray,
  },
  selectedDatePill: {
    backgroundColor: theme.colors.purple,
    borderColor: theme.colors.purple,
  },
  disabledDatePill: {
    backgroundColor: theme.colors.borderLight,
    borderColor: theme.colors.borderLight,
    opacity: 0.6,
  },
  dayText: {
    fontFamily: theme.fonts.bold,
    fontSize: 10,
    color: theme.colors.gray,
    marginBottom: 4,
  },
  selectedDayText: {
    color: theme.colors.white,
  },
  disabledDayText: {
    color: theme.colors.lightGray,
  },
  dateNumText: {
    fontFamily: theme.fonts.bold,
    fontSize: 16,
    color: theme.colors.dark,
    marginBottom: 4,
  },
  selectedDateNumText: {
    color: theme.colors.white,
  },
  disabledDateNumText: {
    color: theme.colors.lightGray,
  },
  slotBadgeText: {
    fontFamily: theme.fonts.medium,
    fontSize: 9.5,
    color: theme.colors.teal,
  },
  selectedSlotBadgeText: {
    color: theme.colors.white,
  },
  disabledSlotBadgeText: {
    color: theme.colors.lightGray,
  },
  timeSlotCard: {
    backgroundColor: theme.colors.white,
    borderRadius: 16,
    padding: 16,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: theme.colors.borderLight,
  },
  timeSlotHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  openSlotsBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.softLavender,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 4,
    gap: 4,
  },
  openSlotsText: {
    fontFamily: theme.fonts.bold,
    fontSize: 11,
    color: theme.colors.purple,
  },
  timeSubtext: {
    fontFamily: theme.fonts.medium,
    fontSize: 11.5,
    color: theme.colors.gray,
    marginBottom: 14,
  },
  periodSection: {
    marginBottom: 14,
  },
  periodHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 10,
  },
  periodTitle: {
    fontFamily: theme.fonts.bold,
    fontSize: 12.5,
    color: theme.colors.dark,
  },
  slotsGrid: {
    flexDirection: 'row',
    gap: 8,
  },
  timeSlotBtn: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.white,
    borderWidth: 1,
    borderColor: theme.colors.borderGray,
    position: 'relative',
  },
  selectedTimeSlotBtn: {
    backgroundColor: theme.colors.purple,
    borderColor: theme.colors.purple,
  },
  disabledTimeSlotBtn: {
    backgroundColor: theme.colors.borderLight,
    borderColor: theme.colors.borderLight,
    opacity: 0.5,
  },
  timeSlotText: {
    fontFamily: theme.fonts.bold,
    fontSize: 12,
    color: theme.colors.dark,
  },
  selectedTimeSlotText: {
    color: theme.colors.white,
  },
  disabledTimeSlotText: {
    color: theme.colors.lightGray,
  },
  fastestBadge: {
    position: 'absolute',
    top: -10,
    backgroundColor: theme.colors.yellow,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  fastestBadgeText: {
    fontFamily: theme.fonts.extraBold,
    fontSize: 8.5,
    color: theme.colors.black,
    letterSpacing: 0.5,
  },
  bottomBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: theme.colors.white,
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 20,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    shadowColor: theme.colors.pureBlack,
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 8,
  },
  confirmBtn: {
    backgroundColor: theme.colors.purple,
    borderRadius: 25,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  confirmBtnText: {
    fontFamily: theme.fonts.bold,
    fontSize: 14,
    color: theme.colors.white,
    letterSpacing: 0.5,
  },
});
