import { StyleSheet } from 'react-native';
import { theme } from '../../../config/theme';

export const styles = StyleSheet.create({
  headerWrapper: {
    alignItems: 'center',
    paddingTop: theme.spacing.md,
    marginBottom: theme.spacing.sm,
  },
  logoImage: {
    width: 180,
    height: 54,
  },
  cardContainer: {
    backgroundColor: theme.colors.white,
    borderRadius: 24,
    paddingHorizontal: theme.spacing.lg,
    paddingTop: theme.spacing.lg,
    paddingBottom: theme.spacing.xl,
    marginHorizontal: 16,
    marginTop: theme.spacing.xs,
    marginBottom: theme.spacing.xxl,
    shadowColor: theme.colors.black,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 8,
    borderWidth: 1,
    borderColor: theme.colors.cardBorderSubtle,
    alignItems: 'center',
  },
  illustrationWrapper: {
    width: '100%',
    height: 297,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  title: {
    fontFamily: theme.fonts.bold,
    fontSize: 18,
    color: theme.colors.black,
    textAlign: 'center',
    marginBottom: 6,
  },
  subtitle: {
    fontFamily: theme.fonts.regular,
    fontSize: 13,
    color: theme.colors.gray,
    textAlign: 'center',
    paddingHorizontal: 12,
    marginBottom: 24,
    lineHeight: 18,
  },
  otpContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    paddingHorizontal: 4,
    marginBottom: 20,
  },
  otpInputBox: {
    width: 44,
    height: 52,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.colors.borderGray,
    backgroundColor: theme.colors.bgLight,
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 20,
    fontFamily: theme.fonts.bold,
    color: theme.colors.black,
    textAlign: 'center',
  },
  otpInputBoxFocused: {
    borderColor: theme.colors.purple,
    borderWidth: 2,
    backgroundColor: theme.colors.white,
  },
  resendContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 24,
  },
  resendText: {
    fontFamily: theme.fonts.regular,
    fontSize: 13,
    color: theme.colors.gray,
  },
  timerText: {
    fontFamily: theme.fonts.bold,
    color: theme.colors.red,
  },
  resendLink: {
    fontFamily: theme.fonts.bold,
    color: theme.colors.purple,
    textDecorationLine: 'underline',
  },
  verifyButton: {
    width: '100%',
  },
});
