import { StyleSheet } from 'react-native';
import { theme } from '../../../../config/theme';

export const styles = StyleSheet.create({
  scrollContent: {
    padding: 18,
    alignItems: 'center',
    paddingBottom: 32,
  },
  illustrationWrapper: {
    marginVertical: 8,
  },
  mainTitle: {
    fontFamily: theme.fonts.bold,
    fontSize: 22,
    color: theme.colors.navy,
    textAlign: 'center',
    marginBottom: 4,
  },
  mainSubtitle: {
    fontFamily: theme.fonts.medium,
    fontSize: 13,
    color: theme.colors.gray,
    textAlign: 'center',
    marginBottom: 20,
  },
  detailsCard: {
    width: '100%',
    backgroundColor: theme.colors.white,
    borderRadius: 20,
    padding: 16,
    borderWidth: 1.5,
    borderColor: theme.colors.borderGray,
    marginBottom: 20,
    shadowColor: theme.colors.pureBlack,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 6,
    elevation: 2,
  },
  doctorHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  doctorAvatarWrapper: {
    position: 'relative',
    borderRadius: 26,
    overflow: 'visible',
    marginRight: 12,
  },
  onlineDot: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: theme.colors.vibrantGreen,
    borderWidth: 2,
    borderColor: theme.colors.white,
  },
  doctorMeta: {
    flex: 1,
  },
  doctorLabel: {
    fontFamily: theme.fonts.semibold,
    fontSize: 11,
    color: theme.colors.gray,
  },
  doctorName: {
    fontFamily: theme.fonts.bold,
    fontSize: 15,
    color: theme.colors.navy,
  },
  doctorCategory: {
    fontFamily: theme.fonts.medium,
    fontSize: 11,
    color: theme.colors.gray,
  },
  successBadge: {
    backgroundColor: theme.colors.badgeGreen,
    paddingVertical: 6,
    paddingHorizontal: 14,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: theme.colors.dark,
    borderBottomWidth: 3.5,
    borderBottomColor: theme.colors.dark,
    alignItems: 'center',
    justifyContent: 'center',
  },
  successBadgeText: {
    fontFamily: theme.fonts.bold,
    fontSize: 12,
    color: theme.colors.pureBlack,
  },
  divider: {
    height: 1,
    backgroundColor: theme.colors.borderLight,
    marginVertical: 14,
  },
  metaList: {
    gap: 12,
  },
  metaRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  metaLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  metaLabel: {
    fontFamily: theme.fonts.medium,
    fontSize: 12.5,
    color: theme.colors.gray,
  },
  metaValue: {
    fontFamily: theme.fonts.bold,
    fontSize: 12.5,
    color: theme.colors.navy,
  },
  metaTimeSubValue: {
    fontFamily: theme.fonts.bold,
    fontSize: 12.5,
    color: theme.colors.navy,
  },
  yellowNoteBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.noteYellowBg,
    borderRadius: 12,
    padding: 12,
    marginTop: 16,
    borderWidth: 1,
    borderColor: theme.colors.softYellowBorder,
    gap: 10,
  },
  noteIconWrapper: {
    width: 24,
    height: 24,
    borderRadius: 6,
    backgroundColor: theme.colors.noteYellowIconBg,
    justifyContent: 'center',
    alignItems: 'center',
  },
  yellowNoteText: {
    flex: 1,
    fontFamily: theme.fonts.medium,
    fontSize: 11.5,
    color: theme.colors.amberNoteText,
    lineHeight: 16,
  },
  letExpertKnowBtn: {
    width: '100%',
    height: 48,
    borderRadius: 30,
    backgroundColor: theme.colors.purple,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
    shadowColor: theme.colors.purple,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 4,
  },
  letExpertKnowText: {
    fontFamily: theme.fonts.bold,
    fontSize: 14,
    color: theme.colors.white,
  },
  goToHomeBtn: {
    width: '100%',
    height: 48,
    borderRadius: 30,
    backgroundColor: theme.colors.softBlue,
    borderWidth: 1,
    borderColor: theme.colors.softBlueBorder,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  goToHomeText: {
    fontFamily: theme.fonts.bold,
    fontSize: 15,
    color: theme.colors.black,
  },
  cancelBtn: {
    width: '100%',
    height: 46,
    borderRadius: 12,
    backgroundColor: theme.colors.lightRose,
    borderWidth: 1,
    borderColor: theme.colors.roseBorder,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cancelBtnText: {
    fontFamily: theme.fonts.bold,
    fontSize: 14,
    color: theme.colors.red,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: theme.colors.overlayModal,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  cancelModalCard: {
    width: '100%',
    backgroundColor: theme.colors.white,
    borderRadius: 20,
    padding: 20,
  },
  cancelModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  cancelModalTitle: {
    fontFamily: theme.fonts.bold,
    fontSize: 16,
    color: theme.colors.navy,
  },
  closeBtn: {
    padding: 4,
  },
  closeBtnText: {
    fontSize: 16,
    color: theme.colors.gray,
  },
  warningBox: {
    backgroundColor: theme.colors.lightRose,
    borderRadius: 12,
    padding: 12,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: theme.colors.roseBorder,
  },
  warningBoxText: {
    fontFamily: theme.fonts.medium,
    fontSize: 12,
    color: theme.colors.red,
    lineHeight: 16,
  },
  warningBoxHighlight: {
    fontFamily: theme.fonts.bold,
    color: theme.colors.red,
  },
  popupDoctorCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.cream,
    borderRadius: 14,
    padding: 10,
    marginBottom: 20,
  },
  popupBtnRow: {
    flexDirection: 'row',
    gap: 12,
  },
  noBtn: {
    flex: 1,
    height: 44,
    borderRadius: 22,
    backgroundColor: theme.colors.borderGray,
    justifyContent: 'center',
    alignItems: 'center',
  },
  noBtnText: {
    fontFamily: theme.fonts.bold,
    fontSize: 14,
    color: theme.colors.darkText,
  },
  yesBtn: {
    flex: 1,
    height: 44,
    borderRadius: 22,
    borderWidth: 1.5,
    borderColor: theme.colors.red,
    justifyContent: 'center',
    alignItems: 'center',
  },
  yesBtnText: {
    fontFamily: theme.fonts.bold,
    fontSize: 14,
    color: theme.colors.red,
  },
});
