import { StyleSheet } from 'react-native';
import { theme } from '../../../../config/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: 24,
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 32,
  },
  mainTitle: {
    fontFamily: theme.fonts.bold,
    fontSize: 22,
    color: theme.colors.navy,
    textAlign: 'center',
    lineHeight: 28,
    marginTop: 10,
  },
  mainSubtitle: {
    fontFamily: theme.fonts.medium,
    fontSize: 13,
    color: theme.colors.gray,
    textAlign: 'center',
    marginTop: 4,
  },
  avatarGlowContainer: {
    marginVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarRingOuter: {
    width: 170,
    height: 170,
    borderRadius: 85,
    backgroundColor: theme.colors.softPurpleBg,
    borderWidth: 3,
    borderColor: theme.colors.lightPurple,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: theme.colors.indicatorPurple,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 6,
  },
  avatarRingInner: {
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: theme.colors.white,
    justifyContent: 'center',
    alignItems: 'center',
  },
  spinnerWrapper: {
    marginVertical: 8,
  },
  waitingStatusText: {
    fontFamily: theme.fonts.semibold,
    fontSize: 13,
    color: theme.colors.navy,
    textAlign: 'center',
  },
  letExpertKnowBtn: {
    width: '100%',
    height: 48,
    borderRadius: 24,
    backgroundColor: theme.colors.purple,
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 12,
    shadowColor: theme.colors.purple,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
  },
  letExpertKnowText: {
    fontFamily: theme.fonts.bold,
    fontSize: 14,
    color: theme.colors.white,
  },
  stepperContainer: {
    width: '100%',
    backgroundColor: 'transparent',
    paddingVertical: 12,
    paddingHorizontal: 6,
  },
  stepperRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  stepItem: {
    alignItems: 'center',
    width: 95,
  },
  stepCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  stepCircleCompleted: {
    backgroundColor: theme.colors.greenStep,
  },
  stepCircleInnerWhite: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: theme.colors.white,
    justifyContent: 'center',
    alignItems: 'center',
  },
  stepCircleInactive: {
    backgroundColor: theme.colors.white,
    shadowColor: theme.colors.pureBlack,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    elevation: 2,
  },
  stepNumberInactive: {
    fontFamily: theme.fonts.bold,
    fontSize: 16,
    color: theme.colors.subtextSlate,
  },
  stepLine: {
    flex: 1,
    height: 3,
    alignSelf: 'flex-start',
    marginTop: 18.5,
    marginHorizontal: -4,
  },
  stepLineActive: {
    backgroundColor: theme.colors.greenStep,
  },
  stepLineInactive: {
    backgroundColor: theme.colors.borderGray,
  },
  stepLabelCompleted: {
    fontFamily: theme.fonts.bold,
    fontSize: 13,
    color: theme.colors.navy,
    textAlign: 'center',
    lineHeight: 17,
    marginTop: 8,
  },
  stepLabelInactive: {
    fontFamily: theme.fonts.medium,
    fontSize: 13,
    color: theme.colors.gray,
    textAlign: 'center',
    lineHeight: 17,
    marginTop: 8,
  },
});
