import { StyleSheet } from 'react-native';
import { theme } from '../../../../config/theme';

export const styles = StyleSheet.create({
  scrollContent: {
    padding: 16,
    gap: 16,
  },
  topCard: {
    backgroundColor: '#FEF9C3',
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: '#FDE047',
  },
  topCardContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  topLeftCol: {
    flex: 1,
    paddingRight: 8,
  },
  topCardTitle: {
    fontFamily: theme.fonts.bold,
    fontSize: 16,
    color: theme.colors.navy,
    marginBottom: 4,
  },
  topCardSubtitle: {
    fontFamily: theme.fonts.medium,
    fontSize: 12,
    color: theme.colors.gray,
    lineHeight: 16,
  },
  topRightCol: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  inputContainer: {
    flexDirection: 'row',
    backgroundColor: theme.colors.white,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 4,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.colors.borderGray,
  },
  input: {
    flex: 1,
    fontFamily: theme.fonts.medium,
    fontSize: 13,
    color: theme.colors.navy,
    height: 40,
  },
  applyInputBtn: {
    backgroundColor: '#059669',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
  },
  applyInputBtnText: {
    fontFamily: theme.fonts.bold,
    fontSize: 13,
    color: theme.colors.white,
  },
  sectionTitle: {
    fontFamily: theme.fonts.bold,
    fontSize: 15,
    color: theme.colors.navy,
    marginTop: 4,
  },
  offerCard: {
    flexDirection: 'row',
    backgroundColor: theme.colors.white,
    borderRadius: 16,
    overflow: 'hidden',
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
    alignItems: 'center',
  },
  offerTagCol: {
    width: 48,
    alignSelf: 'stretch',
    backgroundColor: '#7C3AED',
    justifyContent: 'center',
    alignItems: 'center',
  },
  offerTagText: {
    width: 70,
    textAlign: 'center',
    fontFamily: theme.fonts.bold,
    fontSize: 11,
    color: theme.colors.white,
    transform: [{ rotate: '-90deg' }],
  },
  offerInfoCol: {
    flex: 1,
    padding: 14,
  },
  offerTitle: {
    fontFamily: theme.fonts.bold,
    fontSize: 14,
    color: theme.colors.navy,
    marginBottom: 4,
  },
  offerSubtitle: {
    fontFamily: theme.fonts.medium,
    fontSize: 11.5,
    color: theme.colors.gray,
    lineHeight: 16,
  },
  offerApplyBtn: {
    backgroundColor: '#0F172A',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
    marginRight: 14,
  },
  offerApplyBtnText: {
    fontFamily: theme.fonts.bold,
    fontSize: 12,
    color: theme.colors.white,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  successCard: {
    width: '100%',
    backgroundColor: '#FEF3C7',
    borderRadius: 20,
    padding: 24,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#FDE047',
  },
  checkCircle: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: '#16A34A',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 14,
  },
  successCouponCode: {
    fontFamily: theme.fonts.bold,
    fontSize: 16,
    color: '#78350F',
    marginBottom: 4,
  },
  successSubtitle: {
    fontFamily: theme.fonts.medium,
    fontSize: 12.5,
    color: '#92400E',
    textAlign: 'center',
    marginBottom: 20,
  },
  woohooButton: {
    paddingVertical: 8,
    paddingHorizontal: 16,
  },
  woohooButtonText: {
    fontFamily: theme.fonts.bold,
    fontSize: 13,
    color: '#1E293B',
    letterSpacing: 0.5,
  },
});
