import { StyleSheet } from 'react-native';
import { theme } from '../../../../config/theme';

export const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: theme.colors.white,
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 40,
  },
  bannerContainer: {
    position: 'relative',
    backgroundColor: '#F3C50B',
    borderRadius: 16,
    overflow: 'hidden',
    marginBottom: 16,
    padding: 16,
    width: '100%',
    alignSelf: 'stretch',
  },
  bannerSvgBackground: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
  },
  bannerContent: {
    zIndex: 2,
    width: '100%',
  },
  bannerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 16,
    width: '100%',
  },
  walletIconCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: theme.colors.white,
    justifyContent: 'center',
    alignItems: 'center',
  },
  bannerLabel: {
    fontFamily: theme.fonts.medium,
    fontSize: 12,
    color: theme.colors.dark,
  },
  bannerBalance: {
    fontFamily: theme.fonts.bold,
    fontSize: 22,
    color: theme.colors.dark,
  },
  addMoneyBannerButton: {
    backgroundColor: theme.colors.pureBlack,
    borderRadius: 12,
    height: 42,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    alignSelf: 'stretch',
  },
  addMoneyBannerButtonText: {
    fontFamily: theme.fonts.bold,
    fontSize: 13,
    color: theme.colors.white,
  },
  infoCalloutBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.softMint,
    borderRadius: 12,
    padding: 12,
    marginBottom: 20,
    gap: 10,
  },
  infoCalloutText: {
    flex: 1,
    fontFamily: theme.fonts.medium,
    fontSize: 12,
    color: theme.colors.darkText,
    lineHeight: 16,
  },
  sectionTitle: {
    fontFamily: theme.fonts.bold,
    fontSize: 16,
    color: theme.colors.dark,
    marginBottom: 12,
  },
  filterRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 16,
  },
  filterPill: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: theme.colors.white,
    borderWidth: 1,
    borderColor: theme.colors.borderLight,
  },
  filterPillActive: {
    backgroundColor: theme.colors.purple,
    borderColor: theme.colors.purple,
  },
  filterPillText: {
    fontFamily: theme.fonts.medium,
    fontSize: 13,
    color: theme.colors.gray,
  },
  filterPillTextActive: {
    fontFamily: theme.fonts.bold,
    color: theme.colors.white,
  },
  dateGroupHeader: {
    fontFamily: theme.fonts.medium,
    fontSize: 12,
    color: theme.colors.gray,
    marginBottom: 10,
  },
  transactionCardGroup: {
    backgroundColor: theme.colors.white,
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 4,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: theme.colors.borderLight,
    shadowColor: theme.colors.pureBlack,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 6,
    elevation: 1,
  },
  transactionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    justifyContent: 'space-between',
  },
  transactionItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
  },
  transactionIconBox: {
    width: 40,
    height: 40,
    borderRadius: 14,
    backgroundColor: '#1E1E1E',
    justifyContent: 'center',
    alignItems: 'center',
  },
  arrowIconText: {
    color: theme.colors.white,
    fontSize: 16,
  },
  transactionDetailsCol: {
    flex: 1,
  },
  transactionTitle: {
    fontFamily: theme.fonts.bold,
    fontSize: 14,
    color: theme.colors.navy,
    marginBottom: 2,
  },
  transactionSubtitle: {
    fontFamily: theme.fonts.medium,
    fontSize: 11.5,
    color: theme.colors.gray,
    marginBottom: 2,
  },
  transactionDate: {
    fontFamily: theme.fonts.regular,
    fontSize: 11,
    color: theme.colors.slateGray,
  },
  transactionAmountGreen: {
    fontFamily: theme.fonts.bold,
    fontSize: 14,
    color: theme.colors.greenIcon,
  },
  transactionAmountRed: {
    fontFamily: theme.fonts.bold,
    fontSize: 14,
    color: theme.colors.coral,
  },
  divider: {
    height: 1,
    backgroundColor: theme.colors.borderLight,
  },
});
