import { StyleSheet } from 'react-native';
import { theme } from '../../../../config/theme';

export const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 110,
  },
  topExpertCard: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 14,
  },
  avatarWrapper: {
    position: 'relative',
    marginRight: 12,
  },
  avatarBox: {
    width: 50,
    height: 50,
    borderRadius: 25,
    overflow: 'hidden',
    backgroundColor: theme.colors.softPurpleBg,
  },
  badgeOverlay: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    backgroundColor: theme.colors.white,
    borderRadius: 7,
  },
  topTextCol: {
    flex: 1,
  },
  topTitle: {
    fontFamily: theme.fonts.bold,
    fontSize: 15,
    color: theme.colors.dark,
    marginBottom: 1,
  },
  topSubtext: {
    fontFamily: theme.fonts.medium,
    fontSize: 12,
    color: theme.colors.gray,
  },
  videoPreviewCard: {
    width: '100%',
    height: 300,
    backgroundColor: '#0F172A',
    borderRadius: 24,
    marginBottom: 16,
    shadowColor: theme.colors.pureBlack,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 3,
    position: 'relative',
    overflow: 'hidden',
  },
  videoPreviewOff: {
    backgroundColor: '#0F172A',
    borderWidth: 1,
    borderColor: '#1E293B',
  },
  cameraOffOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#0F172A',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 10,
    zIndex: 5,
  },
  participantNameBadge: {
    position: 'absolute',
    top: 20,
    left: 20,
    zIndex: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.85)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
  },
  participantName: {
    fontFamily: theme.fonts.bold,
    fontSize: 14,
    color: theme.colors.dark,
  },
  videoStreamContainer: {
    width: 140,
    height: 140,
    borderRadius: 70,
    overflow: 'hidden',
    backgroundColor: theme.colors.softCream,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3,
    borderColor: theme.colors.softPurpleLight,
  },
  cameraStreamImage: {
    width: '100%',
    height: '100%',
    borderRadius: 24,
  },
  tapToOpenText: {
    fontFamily: theme.fonts.regular,
    fontSize: 10,
    color: theme.colors.gray,
    marginTop: 4,
  },
  cameraOffPlaceholder: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    zIndex: 2,
  },
  cameraOffText: {
    fontFamily: theme.fonts.medium,
    fontSize: 13,
    color: '#94A3B8',
  },
  bottomControlBtn: {
    position: 'absolute',
    bottom: 20,
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 5,
    shadowColor: theme.colors.pureBlack,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  leftControlBtn: {
    left: 20,
  },
  rightControlBtn: {
    right: 20,
  },
  controlBtnNavy: {
    backgroundColor: theme.colors.black,
  },
  controlBtnRed: {
    backgroundColor: theme.colors.red,
  },
  infoCard: {
    backgroundColor: theme.colors.white,
    borderRadius: 20,
    padding: 18,
    shadowColor: theme.colors.pureBlack,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 2,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
  },
  sectionHeading: {
    fontFamily: theme.fonts.bold,
    fontSize: 15,
    color: theme.colors.dark,
  },
  infoGridRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  infoGridCol: {
    flex: 1,
  },
  iconLabelGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginBottom: 4,
  },
  gridLabel: {
    fontFamily: theme.fonts.medium,
    fontSize: 11.5,
    color: theme.colors.gray,
  },
  gridValue: {
    fontFamily: theme.fonts.semibold,
    fontSize: 12,
    color: theme.colors.dark,
    lineHeight: 16,
  },
  divider: {
    height: 1,
    backgroundColor: theme.colors.borderLight,
    marginVertical: 14,
  },
  beforeJoinDesc: {
    fontFamily: theme.fonts.regular,
    fontSize: 12.5,
    color: theme.colors.gray,
    marginBottom: 16,
    lineHeight: 18,
  },
  encryptionPillBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.softMint,
    borderRadius: 14,
    padding: 12,
    gap: 10,
  },
  encryptionText: {
    flex: 1,
    fontFamily: theme.fonts.medium,
    fontSize: 11.5,
    color: theme.colors.dark,
    lineHeight: 16,
  },
  minorNoticeBanner: {
    backgroundColor: '#DC2626',
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 16,
    gap: 10,
  },
  minorUserIcon: {
    marginTop: 1,
  },
  minorNoticeText: {
    flex: 1,
    fontFamily: theme.fonts.medium,
    fontSize: 11.5,
    color: theme.colors.white,
    lineHeight: 16,
  },
  bottomBarRow: {
    backgroundColor: theme.colors.white,
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    borderTopWidth: 1,
    borderTopColor: theme.colors.borderLight,
  },
  actionCircleBtn: {
    width: 48,
    height: 48,
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnNavy: {
    backgroundColor: theme.colors.black,
  },
  btnRed: {
    backgroundColor: theme.colors.red,
  },
  greenJoinBtn: {
    flex: 1,
    backgroundColor: '#95DB00',
    borderRadius: 24,
    height: 48,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#0F172A',
    borderBottomWidth: 3.5,
    borderBottomColor: '#0F172A',
  },
  greenJoinBtnText: {
    fontFamily: theme.fonts.bold,
    fontSize: 14,
    color: '#000000',
  },
});
