import { StyleSheet } from 'react-native';
import { theme } from '../../../config/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 40,
  },
  supportCard: {
    backgroundColor: theme.colors.offWhiteCard,
    borderWidth: 1,
    borderColor: theme.colors.peachBorder,
    borderRadius: 22,
    paddingVertical: 10,
    paddingHorizontal: 18,
    alignItems: 'center',
    marginBottom: 20,
  },
  supportTitle: {
    fontFamily: theme.fonts.bold,
    fontSize: 16,
    color: theme.colors.navy,
    marginBottom: 4,
    textAlign: 'center',
  },
  supportSubtitle: {
    fontFamily: theme.fonts.regular,
    fontSize: 12,
    color: theme.colors.slateMuted,
    marginBottom: 18,
    textAlign: 'center',
  },
  sectionTitle: {
    fontFamily: theme.fonts.bold,
    fontSize: 18,
    color: theme.colors.navy,
    marginBottom: 10,
  },
  crisisCard: {
    backgroundColor: theme.colors.offWhiteCard,
    borderWidth: 1,
    borderColor: theme.colors.peachBorder,
    borderRadius: 22,
    paddingVertical: 10,
    paddingHorizontal: 18,
    alignItems: 'center',
    marginBottom: 16,
  },
  iconBadgeBlue: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: theme.colors.softBlue,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
  },
  crisisTitle: {
    fontFamily: theme.fonts.bold,
    fontSize: 16,
    color: theme.colors.navy,
    marginBottom: 4,
    textAlign: 'center',
  },
  crisisSubtitle: {
    fontFamily: theme.fonts.regular,
    fontSize: 13,
    color: theme.colors.slateMuted,
    marginBottom: 12,
    textAlign: 'center',
  },
  phoneText: {
    fontFamily: theme.fonts.bold,
    fontSize: 17.5,
    color: theme.colors.navy,
  },
  courageCard: {
    backgroundColor: theme.colors.pastelBlue,
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 16,
  },
  iconBadgePurple: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: theme.colors.indigo,
    justifyContent: 'center',
    alignItems: 'center',
  },
  courageText: {
    flex: 1,
    fontFamily: theme.fonts.medium,
    fontSize: 12,
    color: theme.colors.charcoal,
    lineHeight: 18.5,
  },
  momentCard: {
    backgroundColor: theme.colors.offWhiteCard,
    borderWidth: 1,
    borderColor: theme.colors.orangeBorder,
    borderRadius: 22,
    paddingHorizontal: 18,
    paddingVertical: 10,
    marginBottom: 16,
  },
  momentTitle: {
    fontFamily: theme.fonts.bold,
    fontSize: 16.5,
    color: theme.colors.navy,
    marginBottom: 12,
  },
  momentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  momentText: {
    flex: 1,
    fontFamily: theme.fonts.regular,
    fontSize: 12,
    color: theme.colors.slateMuted,
    lineHeight: 18,
  },
  familyCard: {
    backgroundColor: theme.colors.softOrange,
    borderWidth: 1,
    borderColor: theme.colors.orangeBorder,
    borderRadius: 22,
    paddingHorizontal: 18,
    paddingVertical: 10,
    marginBottom: 20,
  },
  familyHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  familyTitle: {
    fontFamily: theme.fonts.bold,
    fontSize: 16.5,
    color: theme.colors.navy,
  },
  addNumberBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: theme.colors.emerald,
    borderRadius: 20,
    paddingVertical: 6,
    paddingHorizontal: 14,
    backgroundColor: theme.colors.white,
    gap: 4,
  },
  addNumberBtnText: {
    fontFamily: theme.fonts.bold,
    fontSize: 13.5,
    color: theme.colors.emerald,
  },
  numbersList: {
    backgroundColor: theme.colors.white,
    borderRadius: 16,
    overflow: 'hidden',
  },
  numberItem: {
    paddingVertical: 14,
    paddingHorizontal: 16,
  },
  numberItemBorder: {
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.borderLight,
  },
  numberText: {
    fontFamily: theme.fonts.bold,
    fontSize: 14.5,
    color: theme.colors.navy,
  },
});
