import { StyleSheet } from 'react-native';
import { theme } from '../../../config/theme';

export const styles = StyleSheet.create({
  headerWrapper: {
    alignItems: 'center',
    paddingTop: theme.spacing.md,
  },
  logoImage: {
    width: 180,
    height: 54,
  },
  welcomeBox: {
    alignItems: 'center',
    marginTop: theme.spacing.sm,
    paddingHorizontal: theme.spacing.lg,
    marginBottom: theme.spacing.md,
  },
  welcomeTitle: {
    fontFamily: theme.fonts.bold,
    fontSize: 22,
    color: theme.colors.black,
    textAlign: 'center',
    marginBottom: 6,
  },
  welcomeSubtitle: {
    fontFamily: theme.fonts.regular,
    fontSize: 13,
    color: theme.colors.gray,
    textAlign: 'center',
    lineHeight: 18,
    paddingHorizontal: 8,
  },
  cardContainer: {
    backgroundColor: theme.colors.white,
    borderRadius: 24,
    paddingHorizontal: theme.spacing.lg,
    paddingTop: theme.spacing.lg,
    paddingBottom: theme.spacing.xl,
    marginHorizontal: 16,
    marginBottom: theme.spacing.xxl,
    shadowColor: theme.colors.black,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 8,
    borderWidth: 1,
    borderColor: theme.colors.cardBorderSubtle,
  },
  inputGroup: {
    marginBottom: 16,
  },
  inputLabel: {
    fontFamily: theme.fonts.semibold,
    fontSize: 13,
    color: theme.colors.black,
    marginBottom: 6,
  },
  iconInputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.colors.borderGray,
    borderRadius: 12,
    height: 52,
    paddingHorizontal: 14,
    backgroundColor: theme.colors.white,
  },
  textInput: {
    flex: 1,
    fontFamily: theme.fonts.regular,
    fontSize: 14,
    color: theme.colors.black,
    height: '100%',
  },
  phoneInputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.colors.borderGray,
    borderRadius: 12,
    height: 52,
    paddingHorizontal: 14,
    backgroundColor: theme.colors.white,
  },
  countryCode: {
    fontFamily: theme.fonts.bold,
    fontSize: 14,
    color: theme.colors.black,
    marginRight: 10,
  },
  verticalDivider: {
    width: 1,
    height: 24,
    backgroundColor: theme.colors.borderGray,
    marginRight: 12,
  },
  dropdownTrigger: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: theme.colors.borderGray,
    borderRadius: 12,
    height: 52,
    paddingHorizontal: 14,
    backgroundColor: theme.colors.white,
  },
  dropdownLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  dropdownText: {
    fontFamily: theme.fonts.regular,
    fontSize: 14,
    color: theme.colors.black,
  },
  dropdownPlaceholder: {
    fontFamily: theme.fonts.regular,
    fontSize: 14,
    color: theme.colors.slateGray,
  },
  infoBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginTop: 4,
    marginBottom: 16,
  },
  infoText: {
    fontFamily: theme.fonts.regular,
    fontSize: 12,
    color: theme.colors.gray,
    flex: 1,
    lineHeight: 16,
  },
  checkboxRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 20,
    backgroundColor: theme.colors.bgLight,
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.colors.borderGray,
  },
  checkboxBox: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: theme.colors.purple,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
    marginTop: 2,
    backgroundColor: theme.colors.white,
  },
  checkboxChecked: {
    backgroundColor: theme.colors.purple,
  },
  checkboxLabel: {
    fontFamily: theme.fonts.regular,
    fontSize: 12,
    color: theme.colors.black,
    flex: 1,
    lineHeight: 17,
  },
  highlightText: {
    fontFamily: theme.fonts.bold,
    color: theme.colors.purple,
  },
  sendButton: {
    marginTop: 4,
  },

  modalOverlay: {
    flex: 1,
    backgroundColor: theme.colors.overlayModal,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  modalContent: {
    width: '100%',
    maxHeight: 380,
    backgroundColor: theme.colors.white,
    borderRadius: 16,
    paddingVertical: 12,
    shadowColor: theme.colors.pureBlack,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
  },
  modalTitle: {
    fontFamily: theme.fonts.bold,
    fontSize: 16,
    color: theme.colors.black,
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.borderGray,
  },
  optionItem: {
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.borderLight,
  },
  optionText: {
    fontFamily: theme.fonts.medium,
    fontSize: 14,
    color: theme.colors.black,
  },
  selectedOptionText: {
    fontFamily: theme.fonts.bold,
    color: theme.colors.purple,
  },
});
