import { StyleSheet, Dimensions } from 'react-native';
import { theme } from '../../../config/theme';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: 'transparent',
  },
  backButton: {
    padding: 6,
    marginRight: 8,
  },
  headerTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  headerTitle: {
    fontFamily: theme.fonts.bold,
    fontSize: 18,
    color: theme.colors.navy,
  },
  keyboardView: {
    flex: 1,
  },
  chatScrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 16,
  },
  heroContainer: {
    alignItems: 'center',
    marginBottom: 24,
  },
  heroTitle: {
    fontFamily: theme.fonts.bold,
    fontSize: 28,
    color: theme.colors.navy,
    textAlign: 'center',
    lineHeight: 36,
    marginBottom: 6,
  },
  heroSubtitle: {
    fontFamily: theme.fonts.medium,
    fontSize: 12,
    color: theme.colors.gray,
    textAlign: 'center',
  },
  categorySection: {
    alignItems: 'center',
    marginBottom: 22,
  },
  categoryBadgeCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
    shadowColor: theme.colors.pureBlack,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  promptChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.white,
    borderRadius: 20,
    paddingVertical: 11,
    paddingHorizontal: 18,
    marginBottom: 10,
    shadowColor: theme.colors.pureBlack,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 2,
    borderWidth: 1,
    borderColor: theme.colors.borderLight,
    maxWidth: SCREEN_WIDTH - 40,
  },
  indicatorDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 10,
  },
  promptText: {
    fontFamily: theme.fonts.semibold,
    fontSize: 13.5,
    color: theme.colors.navy,
  },
  chatList: {
    paddingBottom: 16,
  },
  aiMessageRow: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    marginBottom: 16,
  },
  aiBubble: {
    backgroundColor: theme.colors.white,
    borderRadius: 20,
    borderTopLeftRadius: 4,
    paddingVertical: 14,
    paddingHorizontal: 16,
    maxWidth: '85%',
    shadowColor: theme.colors.pureBlack,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
    borderWidth: 1,
    borderColor: theme.colors.borderLight,
  },
  aiMessageText: {
    fontFamily: theme.fonts.medium,
    fontSize: 14,
    color: theme.colors.darkText,
    lineHeight: 20,
    marginBottom: 6,
  },
  timestamp: {
    fontFamily: theme.fonts.regular,
    fontSize: 10.5,
    color: theme.colors.timeGray,
    alignSelf: 'flex-end',
  },
  userMessageRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginBottom: 16,
  },
  userBubble: {
    backgroundColor: theme.colors.userBubbleBg,
    borderRadius: 20,
    borderTopRightRadius: 4,
    paddingVertical: 14,
    paddingHorizontal: 16,
    maxWidth: '85%',
    shadowColor: theme.colors.pureBlack,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
  },
  userMessageText: {
    fontFamily: theme.fonts.medium,
    fontSize: 14,
    color: theme.colors.white,
    lineHeight: 20,
    marginBottom: 6,
  },
  userTimestamp: {
    fontFamily: theme.fonts.regular,
    fontSize: 10.5,
    color: theme.colors.userBubbleSubtext,
    alignSelf: 'flex-end',
  },
  bottomInputWrapper: {
    paddingHorizontal: 16,
    paddingTop: 6,
    paddingBottom: 8,
    backgroundColor: 'transparent',
  },
  inputBarContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.white,
    borderRadius: 28,
    paddingLeft: 20,
    paddingRight: 6,
    paddingVertical: 5,
    shadowColor: theme.colors.pureBlack,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 6,
    borderWidth: 1,
    borderColor: theme.colors.borderLight,
  },
  textInput: {
    flex: 1,
    fontFamily: theme.fonts.regular,
    fontSize: 14,
    color: theme.colors.navy,
    maxHeight: 100,
    paddingVertical: 6,
  },
  sendButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: theme.colors.purple,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 8,
  },
});
