import { StyleSheet } from 'react-native';
import { theme } from '../../../../config/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: 'transparent',
  },
  backButton: {
    padding: 6,
    marginRight: 8,
  },
  headerTitle: {
    fontFamily: theme.fonts.bold,
    fontSize: 18,
    color: theme.colors.navy,
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 40,
  },
  userProfileCard: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    paddingHorizontal: 4,
  },
  avatarContainer: {
    position: 'relative',
    marginRight: 16,
  },
  avatarCircle: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: theme.colors.white,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: theme.colors.softPurpleLight,
    shadowColor: theme.colors.pureBlack,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    overflow: 'hidden',
  },
  avatarImage: {
    width: '100%',
    height: '100%',
    borderRadius: 36,
  },
  cameraBadge: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: theme.colors.purple,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: theme.colors.white,
  },
  userInfo: {
    flex: 1,
  },
  userName: {
    fontFamily: theme.fonts.bold,
    fontSize: 19,
    color: theme.colors.navy,
    marginBottom: 2,
  },
  userPhone: {
    fontFamily: theme.fonts.medium,
    fontSize: 13.5,
    color: theme.colors.gray,
    marginBottom: 3,
  },
  userWelzaaId: {
    fontFamily: theme.fonts.semibold,
    fontSize: 13.5,
    color: theme.colors.purple,
  },
  referCard: {
    position: 'relative',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: theme.colors.cardCream,
    borderRadius: 16,
    padding: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: theme.colors.softAmber,
    shadowColor: theme.colors.pureBlack,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 6,
    elevation: 2,
    overflow: 'hidden',
  },
  referTextContainer: {
    flex: 1,
    marginRight: 12,
    zIndex: 2,
  },
  referTitle: {
    fontFamily: theme.fonts.bold,
    fontSize: 15.5,
    color: theme.colors.navy,
    marginBottom: 4,
  },
  referSubtitle: {
    fontFamily: theme.fonts.medium,
    fontSize: 12,
    color: theme.colors.subtextSlate,
    lineHeight: 17,
  },
  referShareCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: theme.colors.amberStar,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: theme.colors.pureBlack,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
    zIndex: 2,
  },
  cardContainer: {
    backgroundColor: theme.colors.white,
    borderRadius: 16,
    marginBottom: 10,
    paddingHorizontal: 16,
    paddingVertical: 2,
    shadowColor: theme.colors.pureBlack,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 2,
    borderWidth: 1,
    borderColor: theme.colors.borderLight,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 14,
  },
  menuItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  menuItemText: {
    fontFamily: theme.fonts.medium,
    fontSize: 14,
    color: theme.colors.darkText,
  },
  divider: {
    height: 1,
    backgroundColor: theme.colors.borderLight,
  },
  journalCard: {
    backgroundColor: theme.colors.white,
    borderRadius: 16,
    marginBottom: 10,
    padding: 14,
    shadowColor: theme.colors.pureBlack,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 2,
    borderWidth: 1,
    borderColor: theme.colors.borderLight,
  },
  journalHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 10,
  },
  journalPillButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    alignSelf: 'flex-start',
    backgroundColor: theme.colors.white,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: theme.colors.lightGray,
    paddingVertical: 7,
    paddingHorizontal: 16,
    marginTop: 2,
  },
  journalPillContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  journalPillText: {
    fontFamily: theme.fonts.medium,
    fontSize: 12.5,
    color: theme.colors.darkText,
    marginRight: 6,
  },
  versionText: {
    fontFamily: theme.fonts.bold,
    fontSize: 11,
    color: theme.colors.slateGray,
    textAlign: 'center',
    letterSpacing: 0.6,
  },
});
